apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
        otlp:
            protocols:
                grpc:
                http:
                    cors_allowed_origins:
                    - http://*
                    - https://*

    exporters:
        prometheus:
            endpoint: "0.0.0.0:8889"
            namespace: promexample
            const_labels:
                label1: value1

        zipkin:
            endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
            format: proto

        jaeger:
            endpoint: jaeger-all-in-one:14250
            insecure: true

    processors:
        batch:

    service:
        pipelines:
            traces:
                receivers: [otlp]
                exporters: [zipkin, jaeger]
                processors: [batch]
            metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  agent.yaml: |  
    receivers:
        otlp:
            protocols:
                grpc:
                http:
        opencensus:
        jaeger:
            protocols:
                grpc:
                thrift_http:
        zipkin:

    exporters:
        otlp:
            endpoint: "otel-collector:4317"
            insecure: true
        logging:
            loglevel: debug

    processors:
        batch:

    service:
        pipelines:
            traces:
                receivers: [otlp, zipkin, jaeger]
                processors: [batch]
                exporters: [otlp]
            metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmetrics-config
data:
  vMetrics.yaml: |  
    scrape_configs:
    #- job_name: 'otel-collector'
      - job_name: 'demo_quarkus'
        scrape_interval: 10s
        metrics_path: '/q/metrics'
        static_configs:
          - targets: ['reference-project:8080']
          #- targets: ['otel-collector:8889']
          #- targets: ['otel-collector:8888']