apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-all-in-one
  name: zipkin-all-in-one
spec:
  ports:
  - name: "9411"
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    io.kompose.service: zipkin-all-in-one
  type: LoadBalancer
status:
  loadBalancer: {}
