apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-all-in-one
  name: zipkin-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-all-in-one
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/demo: "true"
        io.kompose.service: zipkin-all-in-one
    spec:
      containers:
      - image: openzipkin/zipkin:latest
        imagePullPolicy: ""
        name: zipkin-all-in-one
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
