apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-all-in-one
  name: jaeger-all-in-one
spec:
  ports:
  - name: "16686"
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: "14268"
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: "14250"
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    io.kompose.service: jaeger-all-in-one
  type: LoadBalancer #ClusterIP
status:
  loadBalancer: {}
