apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: victoriametrics
  name: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: victoriametrics
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/demo: "true"
        io.kompose.service: victoriametrics
    spec:
      containers:
      - args:
        - --promscrape.config=/conf/vMetrics.yaml
        image: victoriametrics/victoria-metrics
        imagePullPolicy: ""
        name: victoriametrics
        ports:
        - containerPort: 8428
        - containerPort: 8089
        - containerPort: 8089
          protocol: UDP
        - containerPort: 2003
        - containerPort: 2003
          protocol: UDP
        - containerPort: 4242
        resources: {}
        volumeMounts:
        - mountPath: /conf
          name: vmetrics-config
      volumes:
      - configMap:
          items:
          - key: vMetrics.yaml
            path: vMetrics.yaml
          name: vmetrics-config
        name: vmetrics-config
      restartPolicy: Always
      serviceAccountName: ""
status: {}
