apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vmagent
  name: vmagent
spec:
  ports:
  - name: "8429"
    port: 8429
    targetPort: 8429
  selector:
    io.kompose.service: vmagent
status:
  loadBalancer: {}
