
# Application image
image:
  # Docker registry
  #registry:  dockerregistry101 #"k3d-registry:5000"
  # Docker repository (application name)
  repository: acrimage101.azurecr.io/acrimage101/demo-quarkus #"demo-quarkus"
  # Docker image tag (application version)
  tag: "latest"

# Number of replicas       
replicas: 1

# Livess probe
livenessProbe:
  url: /q/health/live

# Readines probe  
readinessProbe:
  url: /q/health/ready

# Pod configuration
pod:
  port: 8080

# Service configuration
service:
  port: 8080

  # Database configuration
postgres:
   image: "docker.io/bitnami/postgresql"
   imageTag: "12.2.0"

   service:
     port: 5432  
# Ingress configuration
ingress:
  host: "demo-quarkus.localhost" 
