apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vmagent
  name: vmagent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vmagent
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/demo: "true"
        io.kompose.service: vmagent
    spec:
      containers:
      - args:
        - --promscrape.config=/conf/vMetrics.yaml
        - --remoteWrite.url=http://victoriametrics:8428/api/v1/write
        image: victoriametrics/vmagent
        imagePullPolicy: ""
        name: vmagent
        ports:
        - containerPort: 8429
        resources: {}
        volumeMounts:
        - mountPath: /conf
          name: vmetrics-config
      volumes:
      - configMap:
          items:
          - key: vMetrics.yaml
            path: vMetrics.yaml
          name: vmetrics-config
        name: vmetrics-config
      restartPolicy: Always
      serviceAccountName: ""
status: {}
